<?php
/**
 * Created by PhpStorm.
 * User: vitik
 * Date: 03.11.2018
 * Time: 12:27
 */

namespace common\widgets;



use app\models\Currency;

class CurrencyWidget extends \yii\bootstrap\Widget
{
        public function run()
        {
           // parent::run(); // TODO: Change the autogenerated stub

            $currency=Currency::find()->all();

            return $this->render('currency',['currency'=>$currency]);
        }
}